# Generated by Django 2.2.19 on 2022-09-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингридиентов', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
